# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mikelbon
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-lambda-crud-node2
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-crud-node1

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:730335349976:table/TaskTable

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
